version: '3.8'
services:
  api:
    build: ./back-end
    container_name: backend
    environment:
      - MONGODB_URI=mongodb+srv://nahima697:cocorico@cluster0.c6rvfmj.mongodb.net
    ports:
      - '3000:3000'
    volumes:
      - ./:/c/camioassur/back-end
      - /c/camioassur/back-end/node_modules
  frontend:
    build: ./front-end
    container_name: frontend
    ports:
      - '80:80'
    volumes:
      - ./:/c/camioassur/front-end
      - /c/camioassur/front-end/node_modules