version: '3.8'
services:
  api:
    build: ./back-end
    container_name: backend
    env_file:
      - /back-end/.env
    ports:
      - '3000:3000'
    volumes:
      - ./back-end:/backend
      - /backend/node_modules
  frontend:
    build: ./front-end
    container_name: frontend
    ports:
      - '80:80'
    volumes:
      - ./front-end:/frontend
      - /frontend/node_modules
